[workspace]
members = ["models", "server", "app"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace.dependencies]
models = { path = "./models", package = "buenzlimarks_models" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
