[package]
name = "buenzlimarks"
version = "0.1.0"
edition = "2021"
default-run = "buenzlimarks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "buenzlimarks"
path = "src/main.rs"

[[bin]]
name = "db_reset"
path = "cmd/db_reset.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.6", features = ["macros", "headers"] }
tower-http = { version = "0.3.0", features = ["fs", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.1.2", features = ["v4"] }
oauth2 = "4.2.3"
jwt = "0.16.0"
hmac = { version = "0.12.1", features = ["std"] }
sha2 = "0.10.2"
cfg-if = "1.0.0"
rust-embed = { version = "6.6.0", features = ["axum"] }
mime_guess = "2.0.4"

[dev-dependencies]
mockall = "0.11.3"
tempfile = "3.3.0"
