[book]
authors = ["Remo Senekowitsch"]
language = "en"
multilingual = false
src = "src"
title = "buenzlimarks documentation"

[output.html]
git-repository-url = "https://github.com/senekor/buenzlimarks"
edit-url-template = "https://github.com/senekor/buenzlimarks/edit/main/{path}"
site-url = "/docs/"

[output.html.fold]
enable = true
level = 0
