name: test server
on: [push]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check formatting, run clippy & tests
        run: |
          cd server
          cargo fmt --check
          cargo clippy -- -D warnings
          cargo test
