[package]
name = "buenzlimarks_models"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
strum = { version = "0.25", features = ["strum_macros"] }
strum_macros = "0.25"
uuid = { version = "1.1.2", features = ["v4", "js"] }
